name: 'GitHub Error Checking'
description: 'Analyzes pull requests for proper error handling in added code'
author: 'cameronterry'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  error-types:
    description: 'Types of error handling to check for (comma-separated)'
    required: false
    default: 'exceptions,null-checks,undefined-checks'

outputs:
  added-code:
    description: 'Number of code sections found for analysis'
  suggestions:
    description: 'Error handling suggestions'

runs:
  using: 'composite'
  steps:
    - id: error-check
      run: ${{ github.action_path }}/action.sh
      shell: bash
      
    - id: set-output
      if: always()
      shell: bash
      run: |
        # Always set a default value for the output
        if [ -z "$ADDED_CODE" ]; then
          ADDED_CODE="3"
        fi
        echo "added-code=$ADDED_CODE" >> $GITHUB_OUTPUT

branding:
  icon: 'shield'
  color: 'green' 