name: Test Error Checking

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-error-handling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript Check
        run: npm run typecheck
        
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Check for error handling
        run: node lib/index.js samples/axios.diff
      
      - name: Log results
        run: echo "Analysis complete. See logs above for details." 