name: Test Error Checking

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-error-handling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: TypeScript Check
        run: npm run typecheck
        
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Check sample with LLM integration
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: 'gpt-3.5-turbo'
        run: node lib/src/index.js samples/user-order-services.diff
      
      - name: Verify dist build works with LLM
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: 'gpt-3.5-turbo'
        run: node dist/index.js samples/axios.diff
      
      - name: Test GitHub Action
        uses: ./
        id: action-test
        with:
          github-token: ${{ github.token }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          llm-model: 'gpt-3.5-turbo'
          ignore-patterns: '*.diff,*.yml,*.js'
      
      - name: Log results
        run: |
          echo "Analysis complete. See logs above for details."
          echo "Added code sections: ${{ steps.action-test.outputs.added-code }}"
          echo "Error score: ${{ steps.action-test.outputs.error-score }}"
          echo 'Analysis results saved to file'
          echo '${{ steps.action-test.outputs.analysis-results }}' > analysis-results.json
          
      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: analysis-results.json